# Generated by Django 5.2 on 2025-04-11 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_ingredient_meal'),
        ('users', '0002_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to='users.profile'),
            preserve_default=False,
        ),
    ]
