# Generated by Django 5.2 on 2025-04-11 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('restaurant', 'Restaurant'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
